### ISSUE TITLE
Calendar is stuck loading

### ISSUE THREAD

**Issue by duncanleo** [alphatrl/classmaid#98] opened 2023-08-14 07:00 UTC
<img width="547" alt="image" src="https://github.com/foldaway/smu-shortcuts/assets/7417870/5f2ef673-63d5-49f1-bfde-dde2a0289a4a">

**Comment by alphatrl** [comment] 2023-08-20 15:24
Issue is caused by an invalid date calculation for SMU in the `school-semesters` repo 

https://github.com/foldaway/school-semesters/issues/11

**Comment by alphatrl** [comment] 2024-01-01 02:40
Fixed in https://github.com/foldaway/school-semesters/pull/14

**Closed by alphatrl** 2024-01-01 02:40 UTC
Labels: bug
